/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms.project.pkgfinal;

/**
 *
 * @author rohit
 */
public class Books extends javax.swing.JFrame {

    /**
     * Creates new form Books
     */
    public Books() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BookSearch = new javax.swing.JLabel();
        BookId = new javax.swing.JLabel();
        BookIdTextField = new javax.swing.JTextField();
        AuthorNameLabel1 = new javax.swing.JLabel();
        AuthorNameTextField1 = new javax.swing.JTextField();
        TitleLabel1 = new javax.swing.JLabel();
        TitleTextField1 = new javax.swing.JTextField();
        PublisherNameLabel1 = new javax.swing.JLabel();
        PublisherNameTextField1 = new javax.swing.JTextField();
        NewTransactionLabel1 = new javax.swing.JLabel();
        TransactionIdLabel1 = new javax.swing.JLabel();
        TransactionIdTextField1 = new javax.swing.JTextField();
        MemberNameLabel1 = new javax.swing.JLabel();
        MemberNameTextField1 = new javax.swing.JTextField();
        ISBNLabel1 = new javax.swing.JLabel();
        ISBNTextField1 = new javax.swing.JTextField();
        PhoneLabel1 = new javax.swing.JLabel();
        PhoneTextField1 = new javax.swing.JTextField();
        AddressLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        AddressTextField1 = new javax.swing.JTextField();
        EmailLabel1 = new javax.swing.JLabel();
        EmailTextField1 = new javax.swing.JTextField();
        FineAmountLabel1 = new javax.swing.JLabel();
        FineAmountTextField1 = new javax.swing.JTextField();
        BorrowDateLabel1 = new javax.swing.JLabel();
        BorrowDateTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ReturnDateTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BookSearch.setText("BookSearch ");

        BookId.setText("BookId");

        BookIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookIdTextFieldActionPerformed(evt);
            }
        });

        AuthorNameLabel1.setText("AuthorName");

        TitleLabel1.setText("Title");

        TitleTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitleTextField1ActionPerformed(evt);
            }
        });

        PublisherNameLabel1.setText("PublisherName");

        PublisherNameTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PublisherNameTextField1ActionPerformed(evt);
            }
        });

        NewTransactionLabel1.setText("NewTransaction");

        TransactionIdLabel1.setText("TransactionId");

        TransactionIdTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransactionIdTextField1ActionPerformed(evt);
            }
        });

        MemberNameLabel1.setText("MemberName");

        MemberNameTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberNameTextField1ActionPerformed(evt);
            }
        });

        ISBNLabel1.setText("ISBN");

        ISBNTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISBNTextField1ActionPerformed(evt);
            }
        });

        PhoneLabel1.setText("Phone");

        AddressLabel1.setText("Address");

        jTextField1.setText("jTextField1");

        AddressTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressTextField1ActionPerformed(evt);
            }
        });

        EmailLabel1.setText("Email");

        FineAmountLabel1.setText("FineAmount");

        FineAmountTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FineAmountTextField1ActionPerformed(evt);
            }
        });

        BorrowDateLabel1.setText("BorrowDate");

        BorrowDateTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrowDateTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("ReturnDate");

        ReturnDateTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnDateTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewTransactionLabel1)
                    .addComponent(BookSearch)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AuthorNameLabel1)
                                    .addComponent(TitleLabel1)
                                    .addComponent(BookId)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MemberNameLabel1)
                                    .addComponent(TransactionIdLabel1)
                                    .addComponent(EmailLabel1)
                                    .addComponent(BorrowDateLabel1))))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BookIdTextField)
                            .addComponent(AuthorNameTextField1)
                            .addComponent(TitleTextField1)
                            .addComponent(TransactionIdTextField1)
                            .addComponent(MemberNameTextField1)
                            .addComponent(EmailTextField1)
                            .addComponent(BorrowDateTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PublisherNameLabel1)
                            .addComponent(ISBNLabel1)
                            .addComponent(PhoneLabel1)
                            .addComponent(AddressLabel1)
                            .addComponent(FineAmountLabel1)
                            .addComponent(jLabel1))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ISBNTextField1)
                            .addComponent(PublisherNameTextField1)
                            .addComponent(PhoneTextField1)
                            .addComponent(AddressTextField1)
                            .addComponent(FineAmountTextField1)
                            .addComponent(ReturnDateTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(BookSearch)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BookId)
                    .addComponent(ISBNLabel1)
                    .addComponent(ISBNTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AuthorNameLabel1)
                    .addComponent(AuthorNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PublisherNameLabel1)
                    .addComponent(PublisherNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitleLabel1)
                    .addComponent(TitleTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(NewTransactionLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TransactionIdLabel1)
                            .addComponent(TransactionIdTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PhoneTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PhoneLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MemberNameLabel1)
                    .addComponent(MemberNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddressLabel1)
                    .addComponent(AddressTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailLabel1)
                            .addComponent(EmailTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FineAmountTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FineAmountLabel1))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BorrowDateLabel1)
                            .addComponent(BorrowDateTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ReturnDateTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(370, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BookIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookIdTextFieldActionPerformed

    private void TitleTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TitleTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TitleTextField1ActionPerformed

    private void PublisherNameTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PublisherNameTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PublisherNameTextField1ActionPerformed

    private void TransactionIdTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransactionIdTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TransactionIdTextField1ActionPerformed

    private void MemberNameTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberNameTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MemberNameTextField1ActionPerformed

    private void ISBNTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISBNTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ISBNTextField1ActionPerformed

    private void AddressTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressTextField1ActionPerformed

    private void FineAmountTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FineAmountTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FineAmountTextField1ActionPerformed

    private void BorrowDateTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrowDateTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BorrowDateTextField1ActionPerformed

    private void ReturnDateTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnDateTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnDateTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Books().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel1;
    private javax.swing.JTextField AddressTextField1;
    private javax.swing.JLabel AuthorNameLabel1;
    private javax.swing.JTextField AuthorNameTextField1;
    private javax.swing.JLabel BookId;
    private javax.swing.JTextField BookIdTextField;
    private javax.swing.JLabel BookSearch;
    private javax.swing.JLabel BorrowDateLabel1;
    private javax.swing.JTextField BorrowDateTextField1;
    private javax.swing.JLabel EmailLabel1;
    private javax.swing.JTextField EmailTextField1;
    private javax.swing.JLabel FineAmountLabel1;
    private javax.swing.JTextField FineAmountTextField1;
    private javax.swing.JLabel ISBNLabel1;
    private javax.swing.JTextField ISBNTextField1;
    private javax.swing.JLabel MemberNameLabel1;
    private javax.swing.JTextField MemberNameTextField1;
    private javax.swing.JLabel NewTransactionLabel1;
    private javax.swing.JLabel PhoneLabel1;
    private javax.swing.JTextField PhoneTextField1;
    private javax.swing.JLabel PublisherNameLabel1;
    private javax.swing.JTextField PublisherNameTextField1;
    private javax.swing.JTextField ReturnDateTextField1;
    private javax.swing.JLabel TitleLabel1;
    private javax.swing.JTextField TitleTextField1;
    private javax.swing.JLabel TransactionIdLabel1;
    private javax.swing.JTextField TransactionIdTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
